export const QUERIES = {
  SEARCH_NOTES: `
    SELECT
      Z_PK,
      ZTITLE,
      ZTEXT,
      ZUNIQUEIDENTIFIER,
      ZCREATIONDATE,
      ZMODIFICATIONDATE,
      ZTRASHED,
      ZARCHIVED,
      ZPINNED
    FROM ZSFNOTE
    WHERE
      ZTRASHED = 0
      AND ZPERMANENTLYDELETED = 0
      AND (ZTITLE LIKE ? OR ZTEXT LIKE ?)
    ORDER BY ZMODIFICATIONDATE DESC
    LIMIT ?
  `,

  GET_NOTE: `
    SELECT
      Z_PK,
      ZTITLE,
      ZTEXT,
      ZUNIQUEIDENTIFIER,
      ZCREATIONDATE,
      ZMODIFICATIONDATE,
      ZTRASHED,
      ZARCHIVED,
      ZPINNED
    FROM ZSFNOTE
    WHERE
      ZTRASHED = 0
      AND ZPERMANENTLYDELETED = 0
      AND (ZTITLE = ? OR ZUNIQUEIDENTIFIER = ?)
    LIMIT 1
  `,

  GET_NOTE_PK: `
    SELECT Z_PK
    FROM ZSFNOTE
    WHERE (ZTITLE = ? OR ZUNIQUEIDENTIFIER = ?)
      AND ZTRASHED = 0
      AND ZPERMANENTLYDELETED = 0
    LIMIT 1
  `,

  GET_NOTES_BY_TAG: `
    SELECT
      n.Z_PK,
      n.ZTITLE,
      n.ZTEXT,
      n.ZUNIQUEIDENTIFIER,
      n.ZCREATIONDATE,
      n.ZMODIFICATIONDATE,
      n.ZTRASHED,
      n.ZARCHIVED,
      n.ZPINNED
    FROM ZSFNOTE n
    INNER JOIN Z_5TAGS nt ON n.Z_PK = nt.Z_5NOTES
    INNER JOIN ZSFNOTETAG t ON nt.Z_13TAGS = t.Z_PK
    WHERE
      t.ZTITLE = ?
      AND n.ZTRASHED = 0
      AND n.ZPERMANENTLYDELETED = 0
    ORDER BY n.ZMODIFICATIONDATE DESC
    LIMIT ?
  `,

  GET_RECENT_NOTES: `
    SELECT
      Z_PK,
      ZTITLE,
      ZTEXT,
      ZUNIQUEIDENTIFIER,
      ZCREATIONDATE,
      ZMODIFICATIONDATE,
      ZTRASHED,
      ZARCHIVED,
      ZPINNED
    FROM ZSFNOTE
    WHERE
      ZTRASHED = 0
      AND ZPERMANENTLYDELETED = 0
      AND ZMODIFICATIONDATE >= ?
    ORDER BY ZMODIFICATIONDATE DESC
    LIMIT ?
  `,

  LIST_TAGS: `
    SELECT
      ZTITLE,
      ZUNIQUEIDENTIFIER
    FROM ZSFNOTETAG
    WHERE ZTITLE IS NOT NULL
    ORDER BY ZTITLE
  `,

  GET_BACKLINKS: `
    SELECT
      n.Z_PK,
      n.ZTITLE,
      n.ZTEXT,
      n.ZUNIQUEIDENTIFIER,
      n.ZCREATIONDATE,
      n.ZMODIFICATIONDATE,
      n.ZTRASHED,
      n.ZARCHIVED,
      n.ZPINNED
    FROM ZSFNOTE n
    INNER JOIN ZSFNOTEBACKLINK bl ON n.Z_PK = bl.ZLINKEDBY
    WHERE bl.ZLINKINGTO = ?
      AND n.ZTRASHED = 0
      AND n.ZPERMANENTLYDELETED = 0
    ORDER BY n.ZMODIFICATIONDATE DESC
  `,
} as const;
